sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 8.137.194.184
    port: 3399
    database: sky_take_out
    username: root
    password: Sir1024.
  redis:
    host: 8.137.194.184
    port: 6379
    password: Sir1024.
    database: 0
  minio:
    host: http://8.137.194.184:9000 # 访问地址
    accessKey: Sir1024 # 登录账号
    secretKey: Lxq20422. # 登录账号密码
    bucketName: sky # 文件桶的名称
    bucket: public  # 权限